/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autenticar utilizador e emitir token Bearer */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Token emitido com sucesso */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Token"];
                    };
                };
                /** @description Credenciais inválidas ou campos em falta */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorValidacao"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revogar token actual */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token revogado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorNaoAutenticado"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Criar token adicional para o utilizador autenticado */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nome_token: string;
                    };
                };
            };
            responses: {
                /** @description Token criado com sucesso */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Token"];
                    };
                };
                /** @description Não autenticado */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorNaoAutenticado"];
                    };
                };
                /** @description Campos inválidos */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorValidacao"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorias-documento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar categorias de documento (cursor pagination) */
        get: {
            parameters: {
                query?: {
                    per_page?: number;
                    sort?: "nome" | "slug" | "tipo_movimento" | "created_at";
                    direction?: "asc" | "desc";
                    /** @description Filtro de estado SoftDelete */
                    estado?: "todos" | "somente_ativos" | "somente_inativos";
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["CategoriaDocumento"][];
                            links?: {
                                prev?: string | null;
                                next?: string | null;
                            };
                            meta?: Record<string, never>;
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        put?: never;
        /** Criar categoria de documento */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nome: string;
                        slug: string;
                        /** @enum {string} */
                        tipo_movimento: "debito" | "credito" | "neutro";
                    };
                };
            };
            responses: {
                /** @description Categoria criada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["CategoriaDocumento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorias-documento/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Ver categoria de documento */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categoria encontrada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["CategoriaDocumento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        /** Actualizar categoria de documento */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nome: string;
                        slug: string;
                        /** @enum {string} */
                        tipo_movimento: "debito" | "credito" | "neutro";
                    };
                };
            };
            responses: {
                /** @description Categoria actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["CategoriaDocumento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        post?: never;
        /** Eliminar categoria de documento */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminada com sucesso (hard delete se sem referências; soft delete se referenciada) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorias-documento/{id}/restaurar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Restaurar categoria de documento soft-deleted */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categoria restaurada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["CategoriaDocumento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        trace?: never;
    };
    "/tipos-documento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar tipos de documento (cursor pagination) */
        get: {
            parameters: {
                query?: {
                    per_page?: number;
                    sort?: "nome";
                    direction?: "asc" | "desc";
                    cursor?: string;
                    /** @description Filtra por categoria; 422 se fornecido mas inexistente; sem filtro se omitido */
                    id_categoria?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TipoDocumento"][];
                            links?: {
                                prev?: string | null;
                                next?: string | null;
                            };
                            meta?: Record<string, never>;
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        put?: never;
        /**
         * Criar tipo de documento
         * @description Pelo menos um dos campos espera_* tem de ser true (RN-02, validado via withValidator())
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nome: string;
                        descricao: string;
                        /** Format: uuid */
                        id_categoria: string;
                        /** @enum {string} */
                        posicao_empresa_mae: "fornecedor" | "cliente";
                        espera_data_documento: boolean;
                        espera_fornecedor: boolean;
                        espera_cliente: boolean;
                        espera_valor: boolean;
                    };
                };
            };
            responses: {
                /** @description Tipo de documento criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TipoDocumento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tipos-documento/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Ver tipo de documento */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tipo de documento encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TipoDocumento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        /**
         * Actualizar tipo de documento
         * @description Update completo (PUT semântico); pelo menos um espera_* tem de ser true (RN-02)
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nome: string;
                        descricao: string;
                        /** Format: uuid */
                        id_categoria: string;
                        /** @enum {string} */
                        posicao_empresa_mae: "fornecedor" | "cliente";
                        espera_data_documento: boolean;
                        espera_fornecedor: boolean;
                        espera_cliente: boolean;
                        espera_valor: boolean;
                    };
                };
            };
            responses: {
                /** @description Tipo de documento actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TipoDocumento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        post?: never;
        /**
         * Eliminar tipo de documento
         * @description Hard delete definitivo — TipoDocumento não tem SoftDelete
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminado com sucesso */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar entidades (cursor pagination) */
        get: {
            parameters: {
                query?: {
                    per_page?: number;
                    sort?: "nome" | "nif" | "created_at";
                    direction?: "asc" | "desc";
                    /** @description Filtro de estado SoftDelete */
                    estado?: "todos" | "somente_ativos" | "somente_inativos";
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Entidade"][];
                            links?: {
                                prev?: string | null;
                                next?: string | null;
                            };
                            meta?: Record<string, never>;
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
            };
        };
        put?: never;
        /** Criar entidade */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nome: string;
                        nif: string;
                        e_cliente: boolean;
                        e_fornecedor: boolean;
                        e_empresa_aplicacao: boolean;
                    };
                };
            };
            responses: {
                /** @description Entidade criada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Entidade"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entidades/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Ver entidade */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entidade encontrada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Entidade"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        /** Actualizar entidade */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nome: string;
                        nif: string;
                        e_cliente: boolean;
                        e_fornecedor: boolean;
                        e_empresa_aplicacao: boolean;
                    };
                };
            };
            responses: {
                /** @description Entidade actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Entidade"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        post?: never;
        /** Eliminar entidade */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminada com sucesso */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entidades/{id}/restaurar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Restaurar entidade soft-deleted */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entidade reactivada (deleted_at a null) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Entidade"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        trace?: never;
    };
    "/entidades/{id}/empresa-mae": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Converter entidade em empresa mãe */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entidade convertida em empresa mãe */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Entidade"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        trace?: never;
    };
    "/entidades/{principal}/agrupar-com/{secundaria}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fundir entidade secundária na principal (repontar FKs + hard-delete)
         * @description Reponta o UUID da entidade secundária para o da principal em todas as FKs conhecidas (documentos.id_fornecedor, documentos.id_cliente), une os papéis e_cliente/e_fornecedor por OR (e_empresa_aplicacao da principal fica intocado) e remove a secundária permanentemente (hard-delete, sem soft-delete). Operação atómica — falha faz rollback total. Não há fusão campo-a-campo de dados.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    principal: string;
                    secundaria: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entidades fundidas — devolve a principal actualizada (papéis unidos) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Entidade"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar roles (cursor pagination) */
        get: {
            parameters: {
                query?: {
                    per_page?: number;
                    sort?: "name";
                    direction?: "asc" | "desc";
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Role"][];
                            links?: {
                                prev?: string | null;
                                next?: string | null;
                            };
                            meta?: Record<string, never>;
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
            };
        };
        put?: never;
        /** Criar role */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nome: string;
                        permissoes: string[];
                    };
                };
            };
            responses: {
                /** @description Role criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Role"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Ver role */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Role encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Role"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        /** Actualizar role */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nome?: string;
                        permissoes: string[];
                    };
                };
            };
            responses: {
                /** @description Role actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Role"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        post?: never;
        /** Eliminar role */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminado com sucesso */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar documentos (cursor pagination) */
        get: {
            parameters: {
                query?: {
                    per_page?: number;
                    sort?: "data_documento" | "created_at";
                    direction?: "asc" | "desc";
                    cursor?: string;
                    estado?: components["schemas"]["EstadoDocumento"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Documento"][];
                            links?: {
                                prev?: string | null;
                                next?: string | null;
                            };
                            meta?: Record<string, never>;
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
            };
        };
        put?: never;
        /** Registar documento manual (JSON) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id_fornecedor: string;
                        /** Format: uuid */
                        id_cliente: string;
                        /** Format: uuid */
                        id_categoria: string;
                        valor: number;
                        /** Format: date */
                        data_documento: string;
                    };
                };
            };
            responses: {
                /** @description Documento registado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Documento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receber upload de documento (multipart/form-data) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        ficheiro: string;
                        /** Format: uuid */
                        id_fornecedor: string;
                        /** Format: uuid */
                        id_cliente: string;
                        /** Format: uuid */
                        id_categoria: string;
                        valor: number;
                        /** Format: date */
                        data_documento: string;
                    };
                };
            };
            responses: {
                /** @description Upload recebido; documento em PENDENTE */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Documento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                documento: string;
            };
            cookie?: never;
        };
        /** Ver documento */
        get: {
            parameters: {
                query?: {
                    include?: "historico";
                };
                header?: never;
                path: {
                    documento: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Documento encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Documento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        /** Corrigir documento (Processado → Processado) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documento: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id_fornecedor: string;
                        /** Format: uuid */
                        id_cliente: string;
                        /** Format: uuid */
                        id_categoria: string;
                        valor: number;
                        /** Format: date */
                        data_documento: string;
                    };
                };
            };
            responses: {
                /** @description Documento corrigido */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Documento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        post?: never;
        /** Eliminar documento (qualquer estado) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documento: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminado com sucesso */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento}/reprocessar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocessar documento (Erro → AguardaEnvio) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documento: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        modo: "MODELO" | "FERRAMENTA";
                    };
                };
            };
            responses: {
                /** @description Documento reaberto para reprocessamento */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Documento"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                /** @description Transição inválida ou dados em falta */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorTransicaoInvalida"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documentos/{documento}/ficheiro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descarregar ficheiro do documento */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documento: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stream do ficheiro */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/utilizadores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar utilizadores (cursor pagination) */
        get: {
            parameters: {
                query?: {
                    per_page?: number;
                    sort?: "name" | "email" | "created_at";
                    direction?: "asc" | "desc";
                    estado?: components["schemas"]["FiltroEstadoRegisto"];
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Utilizador"][];
                            links?: {
                                prev?: string | null;
                                next?: string | null;
                            };
                            meta?: Record<string, never>;
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
            };
        };
        put?: never;
        /** Criar utilizador */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** Format: email */
                        email: string;
                        /** @description Mínimo 8 caracteres, maiúsculas e minúsculas, números e símbolos */
                        password: string;
                        password_confirmation: string;
                        /** @description Nome de um role existente (opcional) */
                        role?: string | null;
                    };
                };
            };
            responses: {
                /** @description Utilizador criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Utilizador"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/utilizadores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Ver utilizador (inclui inactivos; o próprio é sempre permitido) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Utilizador encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Utilizador"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
            };
        };
        /** Actualizar utilizador (inclui inactivos) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        /** Format: email */
                        email: string;
                        /** @description Opcional; se omitido a password não é alterada */
                        password?: string | null;
                        password_confirmation?: string;
                    };
                };
            };
            responses: {
                /** @description Utilizador actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Utilizador"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        post?: never;
        /** Eliminar utilizador (hard delete sem referências; soft delete se referenciado) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminado com sucesso (tokens revogados) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                /** @description Auto-eliminação não permitida */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorValidacao"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/utilizadores/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Atribuir role a um utilizador */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        role: string;
                    };
                };
            };
            responses: {
                /** @description Role atribuído com sucesso */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                422: components["schemas"]["ErrorValidacao"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/utilizadores/{id}/restaurar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Restaurar utilizador soft-deleted
         * @description Reactiva um utilizador soft-deleted. Requer a permissão `utilizadores.eliminar`. Falha com 422 se o utilizador não estava inactivo ou se está anonimizado (email `anonimizado+...`).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Utilizador reactivado (deleted_at a null) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Utilizador"];
                        };
                    };
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                /** @description Utilizador não estava inactivo, ou está anonimizado */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorValidacao"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/utilizadores/{id}/anonimizar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Anonimizar utilizador (RGPD Art. 17.º)
         * @description Operação irreversível: substitui os dados pessoais (`name`, `email`, `password`, `remember_token`, `email_verified_at`) por valores não-identificativos, revoga os tokens Sanctum e faz soft delete, numa única transação. Requer a permissão `utilizadores.anonimizar`. Falha com 422 na auto-anonimização ou se o utilizador já está anonimizado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Utilizador anonimizado (dados substituídos, soft-deleted, tokens revogados) */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["schemas"]["ErrorNaoAutenticado"];
                403: components["schemas"]["ErrorSemPermissao"];
                404: components["schemas"]["ErrorNaoEncontrado"];
                /** @description Auto-anonimização não permitida, ou utilizador já anonimizado */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorValidacao"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorValidacao: {
            /** @example 422 */
            status?: number;
            /** @example Os dados fornecidos são inválidos. */
            detail?: string;
            errors?: {
                [key: string]: string[];
            };
        };
        ErrorNaoAutenticado: {
            /** @example 401 */
            status?: number;
            /** @example Não autenticado. */
            detail?: string;
        };
        ErrorNaoEncontrado: {
            /** @example 404 */
            status?: number;
            /** @example Recurso não encontrado. */
            detail?: string;
        };
        ErrorSemPermissao: {
            /** @example 403 */
            status?: number;
            /** @example Sem permissão para aceder a este recurso. */
            detail?: string;
        };
        Token: {
            data?: {
                /** @example 1|abc123... */
                token?: string;
            };
        };
        CategoriaDocumento: {
            /** Format: uuid */
            id?: string;
            nome?: string;
            slug?: string;
            /** @enum {string} */
            tipo_movimento?: "debito" | "credito" | "neutro";
            /**
             * Format: date-time
             * @description ISO 8601 se inactiva; null se activa
             */
            deleted_at?: string | null;
        };
        Entidade: {
            /** Format: uuid */
            id?: string;
            nome?: string;
            nif?: string;
            e_cliente?: boolean;
            e_fornecedor?: boolean;
            e_empresa_aplicacao?: boolean;
            /**
             * Format: date-time
             * @description ISO 8601 se inactiva; null se activa
             */
            deleted_at?: string | null;
        };
        Role: {
            id?: number;
            nome?: string;
            permissoes?: string[];
        };
        Utilizador: {
            id?: number;
            name?: string;
            /** Format: email */
            email?: string;
            roles?: string[];
            /**
             * Format: date-time
             * @description ISO 8601 se inactivo; null se activo
             */
            deleted_at?: string | null;
            /** Format: date-time */
            created_at?: string;
        };
        /**
         * @description Filtro de SoftDelete nas listagens
         * @default somente_ativos
         * @enum {string}
         */
        FiltroEstadoRegisto: "todos" | "somente_ativos" | "somente_inativos";
        /** @enum {string} */
        EstadoDocumento: "PENDENTE" | "ANALISE_MALWARE" | "ANALISE_TEXTO" | "ANALISE_OCR" | "ANALISE_IA_LOCAL" | "ANALISE_CLOUD" | "PROCESSADO" | "ERRO" | "PERIGOSO";
        /** @enum {string} */
        ResultadoEtapa: "SUCESSO" | "FALHA" | "EM_CURSO";
        EtapaDocumento: {
            estado?: components["schemas"]["EstadoDocumento"];
            resultado?: components["schemas"]["ResultadoEtapa"] | null;
            motivo?: string | null;
            id_utilizador?: number | null;
            /** Format: date-time */
            criado_em?: string;
        };
        Documento: {
            /** Format: uuid */
            id?: string;
            estado?: components["schemas"]["EstadoDocumento"];
            nome_ficheiro_original?: string | null;
            valor?: number | null;
            /** Format: date */
            data_documento?: string | null;
            /** Format: uuid */
            id_fornecedor?: string | null;
            /** Format: uuid */
            id_cliente?: string | null;
            /** Format: uuid */
            id_categoria?: string | null;
            /** Format: date-time */
            created_at?: string;
            historico?: components["schemas"]["EtapaDocumento"][];
        };
        TipoDocumento: {
            /** Format: uuid */
            id?: string;
            nome?: string;
            descricao?: string;
            categoria?: components["schemas"]["CategoriaDocumento"];
            /**
             * @description Derivado de categoria.tipo_movimento
             * @enum {string|null}
             */
            tipo_movimento?: "debito" | "credito" | "neutro" | null;
            /** @enum {string} */
            posicao_empresa_mae?: "fornecedor" | "cliente";
            espera_data_documento?: boolean;
            espera_fornecedor?: boolean;
            espera_cliente?: boolean;
            espera_valor?: boolean;
            /** Format: date-time */
            criado_em?: string;
            /** Format: date-time */
            actualizado_em?: string;
        };
        ErrorTransicaoInvalida: {
            /** @example 422 */
            status?: number;
            /** @example Transição de estado inválida: de "PROCESSADO" para "PENDENTE". */
            detail?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
